services:
  web:
    build: .
    container_name: video-streaming-backend
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}

networks:
  default: